import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav className=" flex w-full gap-8 bg-slate-800 p-4 text-white hover:text-slate-200">
          <Link href="/decks">View All Decks</Link>

          <Link href="/">Create New</Link>
        </nav>
        {children}
      </body>
    </html>
  );
}
